spring:
  application:
    name: api
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/todos}
    username: ${DB_USER:app_user}
    password: ${DB_PASSWORD:app_password}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  cache:
    type: redis
    redis:
      cache-null-values: false
      key-prefix: todos
  kafka:
    producer:
      acks: all
      bootstrap-servers: localhost:29092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /documentation.html